name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create release if version changed
        uses: justincy/github-action-npm-release@2.0.2
        id: release

      - name: Log result
        if: ${{ steps.release.outputs.released == 'true' }}
        run: echo "Released version, ID ${{ steps.release.outputs.release_id }}"
